version: "3.9"
services:
  frontend:
    build: 
     context: .
     dockerfile: Dockerfile
    ports:
      - "3003:3003"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: ["yarn", "dev"]
